steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'southamerica-east1-docker.pkg.dev/microservicios-nestjs/image-registry/products-ms',
        '-f',
        'Dockerfile.prod',
        '--platform=linux/amd64',
        '.',
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'southamerica-east1-docker.pkg.dev/microservicios-nestjs/image-registry/products-ms',
      ]

options:
  logging: CLOUD_LOGGING_ONLY
